#line 2 "src/parseLEX.cpp"

#line 4 "src/parseLEX.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer parse_create_buffer
#define yy_delete_buffer parse_delete_buffer
#define yy_flex_debug parse_flex_debug
#define yy_init_buffer parse_init_buffer
#define yy_flush_buffer parse_flush_buffer
#define yy_load_buffer_state parse_load_buffer_state
#define yy_switch_to_buffer parse_switch_to_buffer
#define yyin parsein
#define yyleng parseleng
#define yylex parselex
#define yylineno parselineno
#define yyout parseout
#define yyrestart parserestart
#define yytext parsetext
#define yywrap parsewrap
#define yyalloc parsealloc
#define yyrealloc parserealloc
#define yyfree parsefree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE parserestart(parsein  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int parseleng;

extern FILE *parsein, *parseout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up parsetext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up parsetext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via parserestart()), so that the user can continue scanning by
	 * just pointing parsein at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when parsetext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int parseleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow parsewrap()'s to do buffer switches
 * instead of setting up a fresh parsein.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void parserestart (FILE *input_file  );
void parse_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE parse_create_buffer (FILE *file,int size  );
void parse_delete_buffer (YY_BUFFER_STATE b  );
void parse_flush_buffer (YY_BUFFER_STATE b  );
void parsepush_buffer_state (YY_BUFFER_STATE new_buffer  );
void parsepop_buffer_state (void );

static void parseensure_buffer_stack (void );
static void parse_load_buffer_state (void );
static void parse_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER parse_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE parse_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE parse_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE parse_scan_bytes (yyconst char *bytes,int len  );

void *parsealloc (yy_size_t  );
void *parserealloc (void *,yy_size_t  );
void parsefree (void *  );

#define yy_new_buffer parse_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        parseensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            parse_create_buffer(parsein,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        parseensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            parse_create_buffer(parsein,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *parsein = (FILE *) 0, *parseout = (FILE *) 0;

typedef int yy_state_type;

extern int parselineno;

int parselineno = 1;

extern char *parsetext;
#define yytext_ptr parsetext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up parsetext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	parseleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[61] =
    {   0,
       19,   18,    1,   18,    2,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   10,   18,   18,
       18,16395,16397,   14,   18,   14,   18,   14,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       10,16395,16397, 8203,16396,16397,    8,    3,    5,    7,
        6,    4, 8204,16396,16397, 8205,    9,   16,   15,   17
    } ;

static yyconst flex_int16_t yy_accept[109] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   20,   21,   24,   26,
       28,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   42,   44,   45,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   48,   49,   50,   51,   52,   53,
       54,   56,   57,   57,   57,   57,   57,   57,   57,   58,
       58,   58,   58,   58,   59,   59,   59,   59,   59,   59,

       60,   61,   61,   61,   61,   61,   61,   61
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    5,    6,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    1,    8,    8,    9,    8,   10,   11,
       12,    8,   13,    8,   14,   15,   16,   17,   18,    8,
       19,   20,    8,   21,   22,   23,    8,    8,   24,    8,
        1,    1,    1,    1,   25,    1,   26,   26,   26,   26,

       27,   28,   26,   26,   29,   26,   30,   26,   31,   32,
       26,   33,   26,   26,   34,   35,   36,   26,   26,   26,
       26,   26,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[37] =
    {   0,
        1,    1,    1,    1,    2,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[123] =
    {   0,
        0,   34,   68,    0,    5,    9,  100,  128,  151,  186,
      217,  323,  323,  323,  196,  193,  201,  184,    0,    0,
        0,    0,    0,    0,  205,  204,  203,  220,  323,  195,
        0,  197,    0,    2,    9,   11,   23,   25,   28,   33,
       36,   57,  186,  173,  176,  160,  180,  179,  175,  173,
      172,  171,  160,    0,  323,   74,   23,  160,   17,   50,
       45,   58,   53,   85,   90,   92,  117,  133,  154,  146,
      162,  137,  117,  323,  323,  323,  323,  323,  323,  323,
        0,  323,   87,   13,  100,  103,   61,  255,  323,  124,
       77,  278,  123,  323,   76,  159,  125,  161,  122,  323,

      112,  178,  135,  183,   86,  144,  323,  302,  305,   98,
       96,   82,   65,   62,   24,  307,  309,  311,  313,  315,
      317,  319
    } ;

static yyconst flex_int16_t yy_def[123] =
    {   0,
      108,  108,  108,    2,    3,    2,    3,    7,  109,  109,
      107,  107,  107,  107,  107,  107,  107,  107,  110,  111,
      112,  113,  114,  115,  107,  107,  107,  107,  107,  107,
      111,  116,  116,  116,  116,  116,  117,  118,  119,  120,
      121,  122,  107,  107,  107,  107,  110,  111,  112,  113,
      114,  115,  107,   28,  107,   28,  107,  116,  116,  116,
      116,  116,  116,  117,  118,  119,  120,  121,  122,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
       56,  107,  116,  116,  116,  116,  116,  107,  107,  107,
      116,  116,  116,  107,  107,  107,  107,  107,  107,  107,

      116,  116,   92,   92,   92,  116,    0,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107
    } ;

static yyconst flex_int16_t yy_nxt[360] =
    {   0,
      107,   13,   14,   25,   25,   59,   26,   59,   27,   27,
       15,   28,   27,   27,   59,   28,   59,   16,   59,   60,
       17,   62,   59,   61,   82,   82,   52,   58,   59,   58,
       59,   92,   58,   59,   18,   13,   14,   58,   59,   63,
       58,   59,   19,   83,   15,   20,   21,   58,   22,   58,
       59,   16,   58,   23,   17,   59,   24,   58,   59,   84,
       58,   58,   59,   59,   51,   85,   59,   50,   18,   13,
       14,   25,   25,   86,   26,   80,   80,   94,   15,  107,
       81,   58,   59,   87,   49,   16,   74,   93,   17,   58,
       59,   75,   59,   76,   58,   59,   58,   59,   48,   99,

       47,   89,   18,   12,   12,   59,   12,   58,   59,   58,
      101,   29,   93,   29,   58,   29,   58,   59,   77,   91,
       30,   58,   59,   94,  100,  100,   94,   29,   59,   29,
       29,   29,   29,   95,   78,   29,   19,   58,   59,   31,
       21,   58,   22,   90,   58,   94,   90,   23,   99,   59,
       24,   12,   13,   14,   12,   79,   58,   58,   58,   59,
       94,   33,   94,   89,   88,   59,   53,   95,   34,   95,
       96,   35,   79,   78,   77,   97,   76,   97,   58,   94,
       75,   74,   99,   59,   99,   36,   12,   13,   14,   12,
       73,   72,   58,   71,   37,   70,   33,   38,   39,   58,

       40,  106,   59,   34,   58,   41,   35,   45,   42,   54,
       53,   53,   46,   45,   44,   43,  107,  107,  107,  107,
       36,   55,   55,  107,  107,   56,   54,  107,  107,  107,
      107,   57,  107,   57,  107,   57,  107,  107,  107,  107,
       57,  107,  107,  107,  107,  107,  107,   57,  107,   57,
       57,   57,   57,  107,  107,   57,   94,  107,  107,  107,
      107,  107,  107,   95,   96,  107,  107,  107,  107,  107,
      107,   97,  107,  107,  107,  107,   98,  107,   99,   94,
      107,  107,  107,   59,  107,  107,  102,  103,  107,  107,
      107,  107,  107,  107,  104,  107,  107,  107,  107,  105,

      107,  106,   12,   12,   12,   32,   32,   32,   58,   58,
       64,   64,   65,   65,   66,   66,   67,   67,   68,   68,
       69,   69,   11,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107
    } ;

static yyconst flex_int16_t yy_chk[360] =
    {   0,
        0,    1,    1,    4,    4,   33,    4,   34,    5,    5,
        1,    5,    6,    6,   35,    6,   36,    1,   84,   33,
        1,   35,   59,   34,   57,   57,  115,   37,   37,   38,
       38,   84,   39,   39,    1,    2,    2,   40,   40,   36,
       41,   41,    2,   59,    2,    2,    2,   37,    2,   38,
       61,    2,   39,    2,    2,   60,    2,   40,   63,   60,
       41,   42,   42,   62,  114,   61,   87,  113,    2,    3,
        3,    3,    3,   62,    3,   56,   56,   95,    3,   56,
       56,   42,   91,   63,  112,    3,   64,   87,    3,   64,
       64,   65,   83,   66,   65,   65,   66,   66,  111,   95,

      110,   85,    3,    7,    7,   85,    7,  105,   86,   64,
       91,    7,   86,    7,   65,    7,   66,  101,   67,   83,
        7,   67,   67,   99,   93,   90,   97,    7,   93,    7,
        7,    7,    7,   97,   68,    7,    8,   68,   68,    8,
        8,   67,    8,   73,  103,  106,   72,    8,   97,  106,
        8,    9,    9,    9,    9,   69,  103,   68,   69,   69,
       96,    9,   98,   71,   70,   58,   53,   96,    9,   98,
       98,    9,   52,   51,   50,   96,   49,   98,   69,  102,
       48,   47,   96,  102,   98,    9,   10,   10,   10,   10,
       46,   45,  104,   44,   10,   43,   10,   10,   10,  104,

       10,  102,   32,   10,  104,   10,   10,   30,   10,   27,
       26,   25,   18,   17,   16,   15,   11,    0,    0,    0,
       10,   28,   28,    0,    0,   28,   28,    0,    0,    0,
        0,   28,    0,   28,    0,   28,    0,    0,    0,    0,
       28,    0,    0,    0,    0,    0,    0,   28,    0,   28,
       28,   28,   28,    0,    0,   28,   88,    0,    0,    0,
        0,    0,    0,   88,   88,    0,    0,    0,    0,    0,
        0,   88,    0,    0,    0,    0,   88,    0,   88,   92,
        0,    0,    0,   92,    0,    0,   92,   92,    0,    0,
        0,    0,    0,    0,   92,    0,    0,    0,    0,   92,

        0,   92,  108,  108,  108,  109,  109,  109,  116,  116,
      117,  117,  118,  118,  119,  119,  120,  120,  121,  121,
      122,  122,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107
    } ;

extern int parse_flex_debug;
int parse_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *parsetext;
#line 1 "src/parser.l"
#line 2 "src/parser.l"
#include <iostream>
#include <cstdlib>
#include "parseYY.hpp"
using namespace std ;

#define E_RLC 1
#define E_IV  2
#define E_GM  3
#define E_OUT 4
#define E_SIM 5

#define yylval parselval

int current= 0;
int amount = 0;





#line 637 "src/parseLEX.cpp"

#define INITIAL 0
#define INT 1
#define VALUE 2
#define R_PREFIX 3
#define R_FNAME 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int parselex_destroy (void );

int parseget_debug (void );

void parseset_debug (int debug_flag  );

YY_EXTRA_TYPE parseget_extra (void );

void parseset_extra (YY_EXTRA_TYPE user_defined  );

FILE *parseget_in (void );

void parseset_in  (FILE * in_str  );

FILE *parseget_out (void );

void parseset_out  (FILE * out_str  );

int parseget_leng (void );

char *parseget_text (void );

int parseget_lineno (void );

void parseset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int parsewrap (void );
#else
extern int parsewrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( parsetext, parseleng, 1, parseout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( parsein )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( parsein ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, parsein))==0 && ferror(parsein)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(parsein); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int parselex (void);

#define YY_DECL int parselex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after parsetext and parseleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( parseleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(parsetext[parseleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 63 "src/parser.l"

#line 833 "src/parseLEX.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)parsealloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in parselex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! parsein )
			parsein = stdin;

		if ( ! parseout )
			parseout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			parseensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				parse_create_buffer(parsein,YY_BUF_SIZE );
		}

		parse_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of parsetext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 108 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 323 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 64 "src/parser.l"
{
  /*  Ignore */
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 68 "src/parser.l"
{
   printf("\n");
   /* reset */
   BEGIN INITIAL ;
   amount = current = 0;
   return T_EOL;
}
	YY_BREAK
case 3:
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up parsetext again */
YY_RULE_SETUP
#line 76 "src/parser.l"
{
   printf("[VCCS(%s)]",parsetext);
   yylval.sv = parsetext;
   BEGIN INT;
   amount = 4 ;
   current = E_GM;
   return T_GID;
}
	YY_BREAK
case 4:
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up parsetext again */
YY_RULE_SETUP
#line 85 "src/parser.l"
{
   printf("[Voltage(%s)]",parsetext);
   yylval.sv = parsetext;
   BEGIN INT;
   amount = 2;
   current = E_IV ;
   return T_VSRC;
}
	YY_BREAK
case 5:
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up parsetext again */
YY_RULE_SETUP
#line 94 "src/parser.l"
{
   printf("[Current(%s)]",parsetext);
   yylval.sv = parsetext ;
   BEGIN INT ;
   amount = 2;
   current = E_IV ;
   return T_ISRC;
}
	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up parsetext again */
YY_RULE_SETUP
#line 103 "src/parser.l"
{
   printf("[Resistor(%s)]",parsetext);
   yylval.sv = parsetext ;
   BEGIN INT;
   amount = 2;
   current = E_RLC ;
   return T_RID;
}
	YY_BREAK
case 7:
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up parsetext again */
YY_RULE_SETUP
#line 112 "src/parser.l"
{
   printf("[Inductor(%s)]",parsetext);
   yylval.sv = parsetext ;
   BEGIN INT;
   amount = 2;
   current = E_RLC ;
   return T_LID;
}
	YY_BREAK
case 8:
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up parsetext again */
YY_RULE_SETUP
#line 121 "src/parser.l"
{
   printf("[Capacitor(%s)]",parsetext);
   yylval.sv = parsetext ;
   BEGIN INT;
   amount = 2;
   current = E_RLC ;
   return T_CID;
}
	YY_BREAK
case 9:
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up parsetext again */
YY_RULE_SETUP
#line 130 "src/parser.l"
{
   printf("[OUT]");
   BEGIN INT;
   amount = 2 ;
   current = E_OUT ;
   return T_OUT;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "src/parser.l"
{
   printf("INTEGER(%s)",parsetext);
   yylval.iv = atoi(parsetext) ;
   if ((-- amount) == 0) {
      switch(current) {
         case E_RLC :
            BEGIN VALUE ; amount = 1 ; break ;
         case E_IV  :
            BEGIN VALUE ; amount = 2 ; break ;
         case E_GM  :
            BEGIN VALUE ; amount = 1 ; break ;
         case E_OUT :
            BEGIN INITIAL;current = 0 ; break ;
      }
   }
   return T_INTEGER;
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 156 "src/parser.l"
{
   printf("INTEGER(%s)",parsetext);
   yylval.iv = atoi(parsetext) ;
   if ((-- amount) == 0) {
      switch(current) {
         case E_RLC :
         case E_IV  :
         case E_GM  :
         case E_OUT :
            BEGIN INITIAL;current = 0 ; break ;
         case E_SIM:
            BEGIN R_FNAME; break ;
      }
   }
   return T_INTEGER;
}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 173 "src/parser.l"
{
   printf("DOUBLE(%s)",parsetext);
   yylval.dv = atof(parsetext) ;
   if ((-- amount) == 0) {
      switch(current) {
         case E_RLC :
         case E_IV  :
         case E_GM  :
         case E_OUT :
            BEGIN INITIAL;current = 0 ; break ;
         case E_SIM:
            BEGIN R_FNAME; break ;
      }
   }
   return T_DOUBLE;
}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 190 "src/parser.l"
{
   printf("DOUBLE(%s)",parsetext);
   yylval.dv = atof(parsetext) ;
   BEGIN R_PREFIX;
   return T_DOUBLE;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 197 "src/parser.l"
{
   printf("PREFIX(%s)",parsetext);
   switch(*parsetext) {
      case 'm': yylval.dv = 1e-3; break;
      case 'u': yylval.dv = 1e-6; break;
      case 'n': yylval.dv = 1e-9; break;
      case 'p': yylval.dv = 1e-12; break;
      case 'f': yylval.dv = 1e-15; break;
      case 'k': yylval.dv = 1e+3; break;
      case 'K': yylval.dv = 1e+3; break;
      case 'M': yylval.dv = 1e+6; break;
      case 'G': yylval.dv = 1e+9; break;
      case 'T': yylval.dv = 1e+12; break;
   }
   if ((-- amount) == 0) {
      switch(current) {
         case E_RLC :
         case E_IV  :
         case E_GM  :
         case E_OUT :
            BEGIN INITIAL;current = 0 ; break ;
         case E_SIM:
            BEGIN R_FNAME; break ;
      }
   } else {
      BEGIN VALUE ;
   }
   return T_PREFIX;
}
	YY_BREAK
case 15:
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up parsetext again */
YY_RULE_SETUP
#line 227 "src/parser.l"
{
   printf("[Time]");
   BEGIN VALUE ;
   current = E_SIM ;
   amount = 3 ;
   return T_TIME;
}
	YY_BREAK
case 16:
*yy_cp = (yy_hold_char); /* undo effects of setting up parsetext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up parsetext again */
YY_RULE_SETUP
#line 235 "src/parser.l"
{
   printf("[Frequency]");
   BEGIN VALUE ;
   amount = 3;
   current = E_SIM;
   return T_FREQ;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 243 "src/parser.l"
{
   printf("File(%s)" , parsetext);
   yylval.sv = parsetext ;
   BEGIN INITIAL ;
   return T_FNAME;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 249 "src/parser.l"
ECHO;
	YY_BREAK
#line 1219 "src/parseLEX.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(INT):
			case YY_STATE_EOF(VALUE):
			case YY_STATE_EOF(R_PREFIX):
			case YY_STATE_EOF(R_FNAME):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed parsein at a new source and called
			 * parselex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = parsein;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( parsewrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * parsetext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of parselex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			parserestart(parsein  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) parserealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 108 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 108 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 107);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up parsetext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					parserestart(parsein );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( parsewrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve parsetext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void parserestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        parseensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            parse_create_buffer(parsein,YY_BUF_SIZE );
	}

	parse_init_buffer(YY_CURRENT_BUFFER,input_file );
	parse_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void parse_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		parsepop_buffer_state();
	 *		parsepush_buffer_state(new_buffer);
     */
	parseensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	parse_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (parsewrap()) processing, but the only time this flag
	 * is looked at is after parsewrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void parse_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	parsein = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE parse_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) parsealloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in parse_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) parsealloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in parse_create_buffer()" );

	b->yy_is_our_buffer = 1;

	parse_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with parse_create_buffer()
 * 
 */
    void parse_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		parsefree((void *) b->yy_ch_buf  );

	parsefree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a parserestart() or at EOF.
 */
    static void parse_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	parse_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then parse_init_buffer was _probably_
     * called from parserestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void parse_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		parse_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void parsepush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	parseensure_buffer_stack();

	/* This block is copied from parse_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from parse_switch_to_buffer. */
	parse_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void parsepop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	parse_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		parse_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void parseensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)parsealloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in parseensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)parserealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in parseensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE parse_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) parsealloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in parse_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	parse_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to parselex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       parse_scan_bytes() instead.
 */
YY_BUFFER_STATE parse_scan_string (yyconst char * yystr )
{
    
	return parse_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to parselex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE parse_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) parsealloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in parse_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = parse_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in parse_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up parsetext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		parsetext[parseleng] = (yy_hold_char); \
		(yy_c_buf_p) = parsetext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		parseleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int parseget_lineno  (void)
{
        
    return parselineno;
}

/** Get the input stream.
 * 
 */
FILE *parseget_in  (void)
{
        return parsein;
}

/** Get the output stream.
 * 
 */
FILE *parseget_out  (void)
{
        return parseout;
}

/** Get the length of the current token.
 * 
 */
int parseget_leng  (void)
{
        return parseleng;
}

/** Get the current token.
 * 
 */

char *parseget_text  (void)
{
        return parsetext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void parseset_lineno (int  line_number )
{
    
    parselineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see parse_switch_to_buffer
 */
void parseset_in (FILE *  in_str )
{
        parsein = in_str ;
}

void parseset_out (FILE *  out_str )
{
        parseout = out_str ;
}

int parseget_debug  (void)
{
        return parse_flex_debug;
}

void parseset_debug (int  bdebug )
{
        parse_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from parselex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    parsein = stdin;
    parseout = stdout;
#else
    parsein = (FILE *) 0;
    parseout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * parselex_init()
     */
    return 0;
}

/* parselex_destroy is for both reentrant and non-reentrant scanners. */
int parselex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		parse_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		parsepop_buffer_state();
	}

	/* Destroy the stack itself. */
	parsefree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    parsefree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * parselex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *parsealloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *parserealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void parsefree (void * ptr )
{
	free( (char *) ptr );	/* see parserealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 249 "src/parser.l"



int parsewrap(void) {
   return 1;
}

